AWSTemplateFormatVersion: 2010-09-09

Parameters: 
  Stage:
    Description: Stage
    Type: String
    AllowedValues:
      - dev
      - stg
      - rls
  ProjectName:
    Type: String
    Default: seat-info

  WebACLName:
    Type: String
    Default: waf-acl

  BucketName:
    Type: String
    Default: waf-log-bucket

Resources: 
 # -------------------------------------
 # Waf logs bucket
 # -------------------------------------
  S3Backet:
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: !Sub ${Stage}-${ProjectName}-${AWS::AccountId}-${BucketName}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256 
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

 # -------------------------------------
 # Firehose
 # -------------------------------------
  DeliveryStream:
    Type: "AWS::KinesisFirehose::DeliveryStream"
    Properties:
      DeliveryStreamName: !Sub waf-logs-${AWS::Region}-${Stage}-${ProjectName}-kinesis
      DeliveryStreamType: DirectPut
      S3DestinationConfiguration:
        BucketARN: !GetAtt S3Backet.Arn
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 5
        CompressionFormat: GZIP
        RoleARN: !GetAtt FirehoseRole.Arn

 # -------------------------------------
 # Iam For Firehose
 # -------------------------------------
  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/'
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub ${AWS::AccountId}
      Policies:
        - 
         PolicyName: !Sub ${Stage}-${ProjectName}-firehose_delivery_role
         PolicyDocument:
           Version: "2012-10-17"
           Statement:
              - 
                Effect: "Allow"
                Action: 
                  - glue:GetTable
                  - glue:GetTableVersion
                  - glue:GetTableVersions
                Resource: "*"
              -
                Effect: "Allow"
                Action: 
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${Stage}-${ProjectName}-${AWS::AccountId}-${BucketName}-${AWS::AccountId}
                  - !Sub arn:aws:s3:::${Stage}-${ProjectName}-${AWS::AccountId}-${BucketName}-${AWS::AccountId}/*
                  - arn:aws:s3:::%FIREHOSE_BUCKET_NAME%
                  - arn:aws:s3:::%FIREHOSE_BUCKET_NAME%/*
              -
                Effect: "Allow"
                Action: 
                  - lambda:InvokeFunction
                  - lambda:GetFunctionConfiguration
                Resource:
                  - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:%FIREHOSE_DEFAULT_FUNCTION%:%FIREHOSE_DEFAULT_VERSION%
              -
                Effect: "Allow"
                Action: 
                  - kms:GenerateDataKey
                  - kms:Decrypt
                Resource:
                  - !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
                Condition:
                  StringEquals:
                    kms:ViaService: !Sub s3.${AWS::Region}.amazonaws.com
                  StringLike:
                    kms:EncryptionContext:aws:s3:arn:
                      - !Sub arn:aws:s3:::${Stage}-${ProjectName}-${AWS::AccountId}-${BucketName}-${AWS::AccountId}/*
                      - !Sub arn:aws:s3:::${Stage}-${ProjectName}-${AWS::AccountId}-${BucketName}-${AWS::AccountId}/%FIREHOSE_BUCKET_PREFIX%*
              -
                Effect: "Allow"
                Action: 
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kinesisfirehose/aws-waf-logs-${AWS::Region}-${WebACLName}:log-stream:*
              -
                Effect: "Allow"
                Action: 
                  - kinesis:DescribeStream
                  - kinesis:GetShardIterator
                  - kinesis:GetRecords
                Resource:
                  - !Sub arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/%FIREHOSE_STREAM_NAME%
              -
                Effect: "Allow"
                Action: 
                  - kms:Decrypt
                Resource:
                  - !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/%SSE_KEY_ID%
                Condition:
                  StringEquals:
                    kms:ViaService: kinesis.%REGION_NAME%.amazonaws.com
                  StringLike:
                    kms:EncryptionContext:aws:kinesis:arn: !Sub arn:aws:kinesis:%REGION_NAME%:${AWS::AccountId}:stream/%FIREHOSE_STREAM_NAME%

 # -------------------------------------
 # Waf ACL
 # -------------------------------------
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub ${Stage}-${ProjectName}-${WebACLName}
      DefaultAction: 
        Allow: {}
      Scope: REGIONAL
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Sub ${Stage}-${ProjectName}-${WebACLName}
        SampledRequestsEnabled: false
      Rules:
        - 
          Name: GeoRestrictRule
          Priority: 0
          Action:
            Block: {}
          Statement:
            NotStatement:
              Statement:
                GeoMatchStatement:
                  CountryCodes:
                    - JP
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${Stage}-${ProjectName}-GeoRestrictRule
            SampledRequestsEnabled: false
        - 
          Name: AWS-AWSManagedRulesAmazonIpReputationList
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          OverrideAction:
            Count: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${Stage}-${ProjectName}-AWSManagedRulesAmazonIpReputationList
            SampledRequestsEnabled: false
        - 
          Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            Count: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${Stage}-${ProjectName}-AWSManagedRulesCommonRuleSet
            SampledRequestsEnabled: false
        - 
          Name: AWS-AWSManagedRulesKnownBadInputsRuleSet
          Priority: 3
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          OverrideAction:
            Count: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${Stage}-${ProjectName}-AWSManagedRulesKnownBadInputsRuleSet
            SampledRequestsEnabled: false
        - 
          Name: AWS-AWSManagedRulesLinuxRuleSet
          Priority: 4
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesLinuxRuleSet
          OverrideAction:
            Count: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${Stage}-${ProjectName}-AWSManagedRulesLinuxRuleSet
            SampledRequestsEnabled: false
        - 
          Name: AWS-AWSManagedRulesUnixRuleSet
          Priority: 5
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesUnixRuleSet
          OverrideAction:
            Count: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${Stage}-${ProjectName}-AWSManagedRulesUnixRuleSet
            SampledRequestsEnabled: false
        # - 
        #   Action: 
        #     Count: {}
        #   Name: Custom-IPaddress-BlackList
        #   Priority: 0
        #   Statement:
        #     IPSetReferenceStatement:
        #       Arn: !GetAtt IPBlackList.Arn
        #   VisibilityConfig:
        #     CloudWatchMetricsEnabled: true
        #     MetricName: Custom-IPaddress-BlackList
        #     SampledRequestsEnabled: false
        -
          Action: 
            Count: {}
          Name: Custom-Ratebased
          Priority: 6
          Statement:
            RateBasedStatement:
              AggregateKeyType: IP
              Limit: 100
              # ScopeDownStatement:
              #   NotStatement:
              #     Statement:
              #       IPSetReferenceStatement:
              #         Arn: !GetAtt IPWhiteList.Arn
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${Stage}-${ProjectName}-Custom-Ratebased
            SampledRequestsEnabled: false

  ALBAttach:
    Type: AWS::WAFv2::WebACLAssociation
    Properties: 
      ResourceArn: { "Fn::ImportValue": !Sub "${Stage}-ALBArn"}
      WebACLArn: !GetAtt WebACL.Arn

  # IPWhiteList:
  #   Type: "AWS::WAFv2::IPSet"
  #   Properties:
  #     Name: Custom-ipaddress-whitelist
  #     Scope: REGIONAL
  #     IPAddressVersion: IPV4
  #     Addresses:
  #       - nnn.nnn.nnn.nnn/32 

  # IPBlackList:
  #   Type: "AWS::WAFv2::IPSet"
  #   Properties:
  #     Name: Custom-ipaddress-blacklist
  #     Scope: REGIONAL
  #     IPAddressVersion: IPV4
  #     Addresses:
  #       - nnn.nnn.nnn.nnn/32